### ISSUE TITLE
Full Screen

### ISSUE THREAD

**Issue by andreimarin90** [andreimarin90/Kobe_HTML#1]
1) Just so it's perfectly clear....this theme is intended to be a FULL SCREEN theme. I have failed to tell you that in the past, so I wanted to be sure you know that this time. :)  For the most part it DOES seem to be a FS theme....but at the same time, I notice that on most pages, the 'footer' band at the bottom is off the screen, so when you scroll, there's a slight "jumping" motion to show it....which is a bit disconcerting to me. Not sure what needs to be done, but in an ideal world, the ENTIRE frame would fit in the browser window....and ALL scrolling would be done WITHIN the full screen frame. Hope that makes sense.

**Comment by arlad** [comment]
Fixed.
